package ddbfns

import (
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/expression"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// DeleteOpts customises [Fns.Delete] operations per each invocation.
type DeleteOpts struct {
	// DisableOptimisticLocking, if true, will skip all logic concerning version attribute.
	DisableOptimisticLocking bool
	// DisableAutoGeneratedTimestamps, if true, will skip all logic concerning timestamp attributes.
	DisableAutoGeneratedTimestamps bool

	// TableName modifies the [dynamodb.DeleteItemInput.TableName]
	TableName *string
	// ReturnConsumedCapacity modifies the [dynamodb.DeleteItemInput.ReturnConsumedCapacity]
	ReturnConsumedCapacity types.ReturnConsumedCapacity
	// ReturnItemCollectionMetrics modifies the [dynamodb.DeleteItemInput.ReturnItemCollectionMetrics]
	ReturnItemCollectionMetrics types.ReturnItemCollectionMetrics
	// ReturnValues modifies the [dynamodb.DeleteItemInput.ReturnValues]
	ReturnValues types.ReturnValue
	// ReturnValuesOnConditionCheckFailure modifies the [dynamodb.DeleteItemInput.ReturnValuesOnConditionCheckFailure].
	ReturnValuesOnConditionCheckFailure types.ReturnValuesOnConditionCheckFailure

	condition expression.ConditionBuilder
	out       interface{}
}

// Decode will decode the [dynamodb.DeleteItemOutput.Attributes] into the given struct pointer.
//
// This opt is only used by DoDelete to avoid having to manually unmarshal the returned item from DynamoDB.
// Unmarshalling error will be returned to caller. If the returned item is empty, unmarshalling will not happen.
//
// Should be used with WithReturnValues or WithReturnValuesOnConditionCheckFailure.
func (o *DeleteOpts) Decode(out interface{}) *DeleteOpts {
	o.out = out
	return o
}

// WithTableName overrides [DeleteOpts.TableName].
func (o *DeleteOpts) WithTableName(tableName string) *DeleteOpts {
	o.TableName = &tableName
	return o
}

// WithReturnValues overrides [DeleteOpts.ReturnValues].
func (o *DeleteOpts) WithReturnValues(returnValues types.ReturnValue) *DeleteOpts {
	o.ReturnValues = returnValues
	return o
}

// WithReturnValuesOnConditionCheckFailure overrides [DeleteOpts.ReturnValuesOnConditionCheckFailure].
func (o *DeleteOpts) WithReturnValuesOnConditionCheckFailure(returnValuesOnConditionCheckFailure types.ReturnValuesOnConditionCheckFailure) *DeleteOpts {
	o.ReturnValuesOnConditionCheckFailure = returnValuesOnConditionCheckFailure
	return o
}

// And adds an expression.And to the condition expression.
func (o *DeleteOpts) And(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *DeleteOpts {
	if o.condition.IsSet() {
		o.condition = o.condition.And(right, other...)
		return o
	}

	switch len(other) {
	case 0:
		o.condition = right
	case 1:
		o.condition = right.And(other[0])
	default:
		o.condition = right.And(other[0], other[1:]...)
	}
	return o
}

// Or adds an expression.And to the condition expression.
func (o *DeleteOpts) Or(right expression.ConditionBuilder, other ...expression.ConditionBuilder) *DeleteOpts {
	if o.condition.IsSet() {
		o.condition = o.condition.Or(right, other...)
		return o
	}

	switch len(other) {
	case 0:
		o.condition = right
	case 1:
		o.condition = right.Or(other[0])
	default:
		o.condition = right.Or(other[0], other[1:]...)
	}
	return o
}
